stages:
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

test:
  stage: test
  image: nikolaik/python-nodejs
  variables:
    SERVER_PORT: 3001
    DB_URL: "mongodb://mongo/nodejs-restify-db"
  services:
    - mongo
  script:
    - npm i
    - npm test